#!/usr/bin/env ruby
#
# Triangular, pentagonal, and hexagonal
# Problem 45
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle     Tn=n(n+1)/2    1, 3, 6,  10, 15, ...
# Pentagonal   Pn=n(3n−1)/2   1, 5, 12, 22, 35, ...
# Hexagonal    Hn=n(2n−1)     1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.
# ---------------------------------------------------------------------------------------------------
#
triangles = Hash.new
pentagons = Hash.new 
hexagons  = Hash.new

def triangle(n)
	return n * (n + 1) / 2
end

def pentagonal(n)
	return n * (3 * n - 1) / 2
end

def hexagonal(n)
	return n * (2 * n - 1)
end

(1..100000000).each do |n|
	tri = triangle(n)
	pen = pentagonal(n)
	hex = hexagonal(n)

	triangles[tri] = n
	pentagons[pen] = n
	hexagons[hex]  = n

	if ((hexagons.has_key? tri) && (pentagons.has_key? tri))
		puts "T#{tri} = P#{pentagons[tri]} = H#{hexagons[tri]} = #{tri}"
		if (tri > 40755)
			exit
		end
	end
end