#!/usr/bin/env ruby
# ---------------------------------------------------------------------------------------------------------------------
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# 
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
# 
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and
# D = |Pk − Pj| is minimised; what is the value of D?
#
# ---------------------------------------------------------------------------------------------------------------------
require "set"

class PentagonalGenerator
	attr_accessor :n, :pentagonals
	def initialize(limit)
		@n = 1
		@limit = limit
		@pentagonals = Set.new
	end

	def each
		while @n <= @limit
			pentagonal = @n * (3 * @n - 1) / 2
			@pentagonals.add pentagonal
			yield pentagonal
			@n += 1
		end
	end
end
 

generator = PentagonalGenerator.new(5000)

# for each p, we're checking to see if we can find pk + pj = p
# if we do, we check that pk - pj is pentagonal
generator.each do |p|
	generator.pentagonals.each do |pk|
		pj = p - pk
		if generator.pentagonals.include? pj
			diff = pk - pj
			if generator.pentagonals.include? diff
				puts diff
				exit
			end

		end
	end
end


